name: DELINQ
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23989
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#a9a9a9'
    - '#d8d7d8'
    - '#827358'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
