name: DELINQ
favicon: null
layout_spectrum: 0.7307635331526399
typography_spectrum: 0.26325655868276954
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.47286448697559536
  lightness: 0.5457621072418988
  saturation: 0.8245752458460629
  rhythmicContrast: 0.5143327279947698
purpose: []
