name: DELINQ
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23989
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#a9a9a9'
    - '#7e7158'
    - '#924900'
    - '#800000'
  brandStrength: 0.875
  lightness: 0.5457621072418988
  saturation: 0.8125
  rhythmicContrast: 0.5143327279947698
purpose: []
